Upgrade API version of metrics' deployments
Upgrade the API version of the Prometheus and Grafana deployments
to the stable version. K8s v1.16 no longer supports beta versions,
creation fails with:
> error: unable to recognize
> "metrics/grafana/manifests/deployment.yaml": no matches for kind
> "Deployment" in version "apps/v1beta2"